// ============================================================================
// HorrorRunSceneSetup.cs
// ============================================================================
// PURPOSE:
//   Builds the procedural horror prototype scene with explicit service and asset
//   references. Closed rooms are generated by the runtime system; this tool only
//   assembles managers, views, content references and deterministic configuration.
// ARCHITECTURAL ROLE:
//   Editor tool (§10) · Editor · Scenes deterministic horror setup.
// KEY RESPONSIBILITIES:
//   - Wire five animated hunters, spatial sound, Lumen 2, curse rules and physical exit/collapse.
//   - Preserve deterministic asset identity when rebuilding the complete expedition.
//   - Preserve unrelated loaded scenes and existing configuration asset identities.
//   - Keep the diagnostic service wired with its document hidden by default.
//   - Supply the HUD compass with the explicit camera aim source.
// DEPENDENCIES:
//   - Runtime layer APIs, existing presentation generators, UnityEditor and URP.
// USAGE NOTES:
//   Editor-only. Refuses Play Mode and a dirty target scene. Run only while owning
//   the Unity lease; saves the target scene and explicitly owned assets only.
// ============================================================================
using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;
using UnityEngine.Rendering.Universal;
using Worsen.Orchestrator;
using Worsen.Domain.Player;
using Worsen.Domain.Hunter;
using Worsen.Domain.Level;
using Worsen.Domain.Procedural;
using Worsen.Domain.Chase;
using Worsen.Domain.Floor;
using Worsen.Domain.Director;
using Worsen.Presentation.Input;
using Worsen.Presentation.DebugOverlay;
using Worsen.Presentation.Horror;
using Worsen.Presentation.ProgressionUI;
using Worsen.Session.Run;
using Worsen.Session.SceneFlow;
using Worsen.Session.Progression;
using Worsen.Session.Expedition;
using Worsen.Session.HorrorEffects;
using Worsen.Presentation.Environment;
using Worsen.Presentation.Audio;
using Worsen.Editor.Horror;
using DistantLands.Lumen;
namespace Worsen.Editor.Scenes
{
    public static class HorrorRunSceneSetup
    {
        public const string ScenePath = "Assets/Scenes/HorrorRun.unity";
        private const string ConfigRoot = "Assets/Resources/ScriptableObjects/";
        [MenuItem("Worsen/Scenes/3 — Build HorrorRun")]
        public static void Build()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("Stop Play Mode first.");
            var previous = SceneManager.GetActiveScene();
            var old = SceneManager.GetSceneByPath(ScenePath);
            if (old.IsValid() && old.isLoaded && old.isDirty) throw new InvalidOperationException("Save your HorrorRun scene edits first.");
            var cake = HorrorArtSetup.EnsureCake();
            HorrorExpansionSetup.BuildContent();
            ConfigureLumenRenderer();
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Additive);
            bool saved = false;
            try
            {
                SceneManager.SetActiveScene(scene);
                var root = Add<HorrorRunSceneRoot>("HorrorRun Scene Root");
                var run = Add<RunSessionManager>("Run Session");
                var flow = Add<SceneFlowManager>("Scene Flow");
                var progression = Add<ProgressionSessionManager>("Progression Session");
                var expedition = Add<ExpeditionSessionManager>("Expedition Session");
                Wire(root, "_effects", Add<HorrorEffectsManager>("Horror Effects Session"));
                Wire(root, "_effectsConfig", Ensure<HorrorEffectsConfig>(ConfigRoot + "Session/HorrorEffects/HorrorEffectsConfig.asset"));
                Wire(root, "_run", run); Wire(root, "_sceneFlow", flow);
                Wire(root, "_progression", progression); Wire(root, "_expedition", expedition);
                Wire(root, "_progressionConfig", Ensure<ProgressionConfig>(ConfigRoot + "Session/Progression/ProgressionConfig.asset"));
                var inputObject = new GameObject("Input Service");
                var inputDriver = inputObject.AddComponent<PlayerInputDriver>();
                var input = inputObject.AddComponent<InputManager>();
                Wire(inputDriver, "_config", Require<InputDriverConfig>(ConfigRoot + "Presentation/Input/InputDriverConfig.asset"));
                Wire(input, "_driver", inputDriver);
                var inputRoute = inputObject.AddComponent<InputOrchestrator>();
                Wire(inputRoute, "_input", input); Wire(inputRoute, "_run", run); Wire(inputRoute, "_sceneFlow", flow);
                Wire(root, "_input", input); Wire(root, "_inputRoute", inputRoute);
                BuildOverlay(root, run);
                BuildPresentation(root, run);
                BuildWorldServices(root, cake);
                var ui = Add<ProgressionUIManager>("Progression UI");
                var uiDriver = ui.GetComponent<ProgressionUIDriver>() ?? ui.gameObject.AddComponent<ProgressionUIDriver>();
                var uiConfig = Ensure<ProgressionUIDriverConfig>(ConfigRoot + "Presentation/ProgressionUI/ProgressionUIDriverConfig.asset");
                var panel = Ensure<PanelSettings>("Assets/Resources/UI/Presentation/ProgressionUI/ProgressionUIPanelSettings.asset");
                panel.scaleMode = PanelScaleMode.ScaleWithScreenSize; panel.referenceResolution = new Vector2Int(1920, 1080);
                panel.themeStyleSheet = Require<ThemeStyleSheet>("Assets/Resources/UI/Presentation/DebugOverlay/DebugOverlayTheme.tss");
                panel.sortingOrder = 50; EditorUtility.SetDirty(panel); AssetDatabase.SaveAssetIfDirty(panel);
                Wire(ui, "_config", uiConfig); Wire(ui, "_driver", uiDriver); Wire(uiDriver, "_panelSettings", panel);
                Wire(root, "_progressionUI", ui);
                Wire(root, "_progressionRoute", ui.gameObject.AddComponent<ProgressionUIOrchestrator>());
                var rootData = new SerializedObject(root);
                rootData.FindProperty("_sourceRevision").stringValue = Fingerprint("Assets/Scripts", "*.cs");
                rootData.FindProperty("_configSnapshotHash").stringValue = Fingerprint("Assets/Resources/ScriptableObjects", "*.asset");
                rootData.ApplyModifiedPropertiesWithoutUndo();
                if (old.IsValid() && old.isLoaded) EditorSceneManager.CloseScene(old, true);
                if (!EditorSceneManager.SaveScene(scene, ScenePath)) throw new InvalidOperationException("Failed to save HorrorRun.");
                saved = true;
                if (!EditorBuildSettings.scenes.Any(value => value.path == ScenePath))
                    EditorBuildSettings.scenes = EditorBuildSettings.scenes.Concat(new[] { new EditorBuildSettingsScene(ScenePath, true) }).ToArray();
            }
            finally
            {
                if (previous.IsValid() && previous.isLoaded) SceneManager.SetActiveScene(previous);
                if (scene.IsValid() && scene.isLoaded && SceneManager.GetActiveScene() != scene) EditorSceneManager.CloseScene(scene, true);
                if (!saved) Debug.LogError("HorrorRun setup did not complete; inspect the preceding error.");
            }
        }

        private static void BuildWorldServices(HorrorRunSceneRoot root, GameObject cake)
        {
            Wire(root, "_level", Add<LevelManager>("Generated Level Graph"));
            Wire(root, "_procedural", Add<ProceduralManager>("Procedural Rooms"));
            Wire(root, "_proceduralConfig", Ensure<ProceduralConfig>(ConfigRoot + "Domain/Procedural/ProceduralConfig.asset"));
            Wire(root, "_proceduralDriverConfig", Ensure<ProceduralDriverConfig>(ConfigRoot + "Domain/Procedural/ProceduralDriverConfig.asset"));
            Wire(root, "_playerFactory", Add<PlayerFactory>("Player Factory"));
            Wire(root, "_playerProfile", Require<PlayerProfile>(ConfigRoot + "Domain/Player/PlayerProfile.asset"));
            Wire(root, "_hunterFactory", Add<HunterFactory>("Hunter Factory"));
            HunterProfile[] roster = Worsen.Editor.Hunter.HorrorHunterSetup.BuildProfiles();
            Wire(root, "_hunterProfile", roster[0]);
            var rootRoster = new SerializedObject(root);
            var profiles = rootRoster.FindProperty("_hunterRoster"); profiles.arraySize = roster.Length;
            for (int i = 0; i < roster.Length; i++) profiles.GetArrayElementAtIndex(i).objectReferenceValue = roster[i];
            rootRoster.ApplyModifiedPropertiesWithoutUndo();
            Wire(root, "_chase", Add<ChaseManager>("Chase Service"));
            Wire(root, "_chaseConfig", Require<ChaseConfig>(ConfigRoot + "Domain/Chase/ChaseConfig.asset"));
            Wire(root, "_director", Add<DirectorManager>("Director Service"));
            Wire(root, "_directorConfig", Require<DirectorConfig>(ConfigRoot + "Domain/Director/DirectorConfig.asset"));
            var floor = Add<FloorManager>("Floor Service");
            var floorConfig = Require<FloorConfig>(ConfigRoot + "Domain/Floor/FloorConfig.asset");
            string driverPath = ConfigRoot + "Domain/Floor/HorrorFloorDriverConfig.asset";
            if (AssetDatabase.LoadAssetAtPath<FloorDriverConfig>(driverPath) == null)
                AssetDatabase.CopyAsset(ConfigRoot + "Domain/Floor/FloorDriverConfig.asset", driverPath);
            var driverConfig = Require<FloorDriverConfig>(driverPath);
            Wire(driverConfig, "_cakePrefab", cake);
            HorrorWorldAssetSetup.Configure(driverConfig, Require<ProceduralDriverConfig>(ConfigRoot + "Domain/Procedural/ProceduralDriverConfig.asset"));
            AssetDatabase.SaveAssetIfDirty(driverConfig);
            Wire(floor.GetComponent<FloorDriver>(), "_config", driverConfig);
            Wire(root, "_floor", floor); Wire(root, "_floorConfig", floorConfig);
        }

        private static void BuildPresentation(HorrorRunSceneRoot root, RunSessionManager run)
        {
            var camera = Add<UnityEngine.Camera>("Main Camera"); camera.tag = "MainCamera";
            camera.backgroundColor = new Color(0.008f, 0.01f, 0.015f); camera.clearFlags = CameraClearFlags.SolidColor;
            camera.gameObject.AddComponent<AudioListener>();
            var data = camera.gameObject.AddComponent<UniversalAdditionalCameraData>(); data.renderPostProcessing = true;
            var cameraManager = Worsen.Editor.Camera.CameraRigSetup.Create(root.transform, camera);
            var postFX = Worsen.Editor.PostFX.PostFXSetup.Create(root.transform);
            Wire(root, "_camera", cameraManager); Wire(root, "_postFX", postFX);
            Route<CameraOrchestrator>(cameraManager.gameObject, run, "_camera", cameraManager);
            Route<PostFXOrchestrator>(postFX.gameObject, run, "_postFX", postFX);
            var audio = Worsen.Editor.Audio.AudioSetup.Create(); Wire(root, "_audio", audio);
            Worsen.Editor.Audio.HorrorAudioSetup.Configure(Require<AudioDriverConfig>(ConfigRoot + "Presentation/Audio/AudioDriverConfig.asset"));
            Route<AudioOrchestrator>(audio.gameObject, run, "_audio", audio);
            var hud = Worsen.Editor.HUD.HUDSetup.Create(root.transform); Wire(root, "_hud", hud);
            Route<HUDOrchestrator>(hud.gameObject, run, "_hud", hud);
            Wire(hud.GetComponent<HUDOrchestrator>(), "_camera", cameraManager);
            var telemetry = Worsen.Editor.Telemetry.TelemetrySetup.CreateService(); Wire(root, "_telemetry", telemetry);
            Route<TelemetryOrchestrator>(telemetry.gameObject, run, "_telemetry", telemetry);
            var horror = Add<HorrorManager>("Horror Atmosphere");
            var horrorDriver = horror.GetComponent<HorrorDriver>() ?? horror.gameObject.AddComponent<HorrorDriver>();
            var config = Ensure<HorrorDriverConfig>(ConfigRoot + "Presentation/Horror/HorrorDriverConfig.asset");
            ConfigureHorrorAudio(config);
            Wire(config, "_lumenFlashlightPrefab", HorrorLumenStyleSetup.EnsureFlashlight());
            Wire(config, "_lumenNearFillPrefab", HorrorLumenStyleSetup.EnsureNearFill());
            var atmosphere = new SerializedObject(config);
            atmosphere.FindProperty("_ambientColor").colorValue = new Color(.14f, .16f, .16f, 1f);
            atmosphere.FindProperty("_nearFillIntensity").floatValue = .8f;
            atmosphere.FindProperty("_nearFillColor").colorValue = new Color(.55f, .65f, .8f, 1f);
            atmosphere.FindProperty("_nearFillSmoothness").floatValue = .35f;
            atmosphere.FindProperty("_nearFillOffMultiplier").floatValue = .2f;
            atmosphere.FindProperty("_fogColor").colorValue = Color.black;
            atmosphere.FindProperty("_backgroundColor").colorValue = Color.black;
            atmosphere.FindProperty("_fogNearMeters").floatValue = 8f;
            atmosphere.FindProperty("_fogFarMeters").floatValue = 24f;
            atmosphere.ApplyModifiedPropertiesWithoutUndo();
            Wire(config, "_attackMaterial", HorrorArtSetup.EnsureAttackMaterial());
            AssetDatabase.SaveAssetIfDirty(config);
            Wire(horror, "_driver", horrorDriver); Wire(horrorDriver, "_outputCamera", camera);
            Wire(horrorDriver, "_fogVolume", HorrorArtSetup.BuildFog(root.transform));
            Wire(root, "_horror", horror); Wire(root, "_horrorConfig", config);
            Wire(root, "_horrorRoute", horror.gameObject.AddComponent<HorrorOrchestrator>());
            var environment = Add<EnvironmentManager>("Medieval Lighting and Dressing");
            Wire(root, "_environment", environment);
            Wire(root, "_environmentConfig", HorrorWorldAssetSetup.BuildEnvironmentConfig());
            Wire(root, "_environmentRoute", environment.gameObject.AddComponent<EnvironmentOrchestrator>());
        }

        private static void BuildOverlay(HorrorRunSceneRoot root, RunSessionManager run)
        {
            const string uiRoot = "Assets/Resources/UI/Presentation/DebugOverlay/";
            var owner = new GameObject("Debug Overlay");
            var document = owner.AddComponent<UIDocument>();
            document.panelSettings = Require<PanelSettings>(uiRoot + "DebugOverlayPanelSettings.asset");
            document.visualTreeAsset = Require<VisualTreeAsset>(uiRoot + "DebugOverlay.uxml");
            var driver = owner.AddComponent<DebugOverlayDriver>();
            var manager = owner.AddComponent<DebugOverlayManager>();
            Wire(driver, "_document", document); Wire(driver, "_panelSettings", document.panelSettings);
            Wire(driver, "_visualTree", document.visualTreeAsset); Wire(manager, "_driver", driver);
            Wire(manager, "_config", Require<DebugOverlayDriverConfig>(ConfigRoot + "Presentation/DebugOverlay/DebugOverlayDriverConfig.asset"));
            Wire(root, "_overlay", manager); Route<DebugOverlayOrchestrator>(owner, run, "_overlay", manager);
            // Keep diagnostics available while hiding the ribbon from the player-facing scene.
            document.enabled = false;
        }
        [MenuItem("Worsen/Scenes/Update Horror Audio Selections")]
        public static void UpdateHorrorAudioSelections()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("Stop Play Mode first.");
            var config = Require<HorrorDriverConfig>(ConfigRoot + "Presentation/Horror/HorrorDriverConfig.asset");
            ConfigureHorrorAudio(config); AssetDatabase.SaveAssetIfDirty(config);
        }
        private static void ConfigureHorrorAudio(HorrorDriverConfig config)
        {
            // Audio owns the expansion soundscape; retain the validated legacy clip reference for older scenes.
            Wire(config, "_attackGrowl", Require<AudioClip>("Assets/External/MonstersSFX/MonstersUpdateOne/FantasyCreatures/Undead/SFX_Undead_MadGrowl_LowPitchVoice_Short_01.wav"));
            var serialized = new SerializedObject(config);
            serialized.FindProperty("_attackGain").floatValue = 0f;
            serialized.FindProperty("_ambienceGain").floatValue = 0f;
            serialized.ApplyModifiedPropertiesWithoutUndo(); EditorUtility.SetDirty(config);
        }
        private static void ConfigureLumenRenderer()
        {
            var pipeline = Require<UniversalRenderPipelineAsset>("Assets/Settings/PC_RPAsset.asset");
            var pipelineData = new SerializedObject(pipeline);
            pipelineData.FindProperty("m_OpaqueDownsampling").intValue = 0;
            pipelineData.FindProperty("m_RequireDepthTexture").boolValue = true;
            pipelineData.FindProperty("m_RequireOpaqueTexture").boolValue = true;
            pipelineData.ApplyModifiedPropertiesWithoutUndo(); AssetDatabase.SaveAssetIfDirty(pipeline);
            var renderer = Require<UniversalRendererData>("Assets/Settings/PC_Renderer.asset");
            var feature = renderer.rendererFeatures.OfType<LumenRendererFeature>().FirstOrDefault();
            if (feature == null)
            {
                feature = ScriptableObject.CreateInstance<LumenRendererFeature>(); feature.name = "Lumen 2 Normals";
                AssetDatabase.AddObjectToAsset(feature, renderer); renderer.rendererFeatures.Add(feature);
            }
            feature.SetActive(true); feature.Create(); renderer.SetDirty();
            EditorUtility.SetDirty(feature); EditorUtility.SetDirty(renderer); AssetDatabase.SaveAssetIfDirty(renderer);
        }
        private static T Add<T>(string name) where T : Component => new GameObject(name).AddComponent<T>();
        private static void Route<T>(GameObject owner, RunSessionManager run, string field, UnityEngine.Object target) where T : Component
        { var route = owner.AddComponent<T>(); Wire(route, "_run", run); Wire(route, field, target); }
        public static void Wire(UnityEngine.Object target, string field, UnityEngine.Object value)
        {
            var serialized = new SerializedObject(target); var property = serialized.FindProperty(field);
            if (property == null) throw new InvalidOperationException(target.GetType().Name + " is missing " + field);
            property.objectReferenceValue = value; serialized.ApplyModifiedPropertiesWithoutUndo(); EditorUtility.SetDirty(target);
        }
        public static T Require<T>(string path) where T : UnityEngine.Object =>
            AssetDatabase.LoadAssetAtPath<T>(path) ?? throw new InvalidOperationException("Missing asset: " + path);
        public static T Ensure<T>(string path) where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path); if (asset != null) return asset;
            EnsureFolder(Path.GetDirectoryName(path).Replace('\\', '/'));
            asset = ScriptableObject.CreateInstance<T>(); AssetDatabase.CreateAsset(asset, path); return asset;
        }
        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/'); EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, Path.GetFileName(path));
        }
        private static string Fingerprint(string directory, string pattern)
        {
            var text = new StringBuilder();
            foreach (string path in Directory.GetFiles(directory, pattern, SearchOption.AllDirectories).OrderBy(path => path, StringComparer.Ordinal))
                text.Append(path.Replace('\\', '/')).Append(System.Environment.NewLine).Append(File.ReadAllText(path)).Append(System.Environment.NewLine);
            using (var hash = SHA256.Create()) return "sha256:" + BitConverter.ToString(hash.ComputeHash(Encoding.UTF8.GetBytes(text.ToString()))).Replace("-", "");
        }
    }
}
