// ============================================================================
// HorrorAudioSetup.cs
// ============================================================================
//
// PURPOSE:
//   Builds the complete horror soundscape from the approved imported and original audio selections.
//   All clip paths are explicit and required, so reimport cannot silently replace important cues with prototype tones.
//
// ARCHITECTURAL ROLE:
//   Editor tool (§10) · Audio.
//
// KEY RESPONSIBILITIES:
//   - Wire all cue banks, Deep Impacts and its stress version, and Claustrophobia danger.
//   - Wire Run 1, Run 2 and Run End for the confirmed pursuit sequence.
//   - Reserve enemy scream clips for enemy feedback; player death uses one subdued body impact.
//   - Keep posture cloth quiet and exertion below critical breathing using dedicated reusable banks.
//   - Preserve existing config identities and save only the two intended config assets.
//
// DEPENDENCIES:
//   - Core cue identities and value data; own Audio presentation stack only.
//
// USAGE NOTES:
//   Coordinator invokes only under the exclusive Unity lease, after imports settle.
//   Selection and derivation provenance lives in Logs/HorrorExpansion/audio; the optional mixer bus references are preserved.
//
// ============================================================================

using System;
using UnityEditor;
using UnityEngine;
using Worsen.Core;
using EntityId = Worsen.Core.EntityId;
using Worsen.Presentation.Audio;

namespace Worsen.Editor.Audio
{
    public static class HorrorAudioSetup
    {
        public const string ConfigPath = "Assets/Resources/ScriptableObjects/Presentation/Audio/AudioSoundscapeDriverConfig.asset";
        [MenuItem("Worsen/Audio/Build Horror Soundscape")]
        public static void BuildMenu() => Configure(AudioConfigGenerator.LoadOrCreateConfig());
        public static AudioSoundscapeDriverConfig Configure(AudioDriverConfig owner)
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling || EditorApplication.isUpdating)
                throw new InvalidOperationException("Soundscape setup requires an idle Editor under the Unity lease.");
            if (owner == null) throw new ArgumentNullException(nameof(owner));
            AudioSoundDefinition[] banks = Banks();
            // Resolve every required clip before modifying any asset.
            const string ambient = "Assets/External/Audio/Horror Elements/Ambient/";
            AudioClip tension = Clip(ambient + "Amb_Deep_impacts.wav");
            AudioClip stress = Clip(ambient + "Amb_Deep_impacts_stress.wav");
            AudioClip danger = Clip(ambient + "Amb_claustrophobia.wav");
            AudioClip intro = Clip(ambient + "Amb_Run_1.wav");
            AudioClip run = Clip(ambient + "Amb_Run_2.wav");
            AudioClip ending = Clip(ambient + "Amb_Run_End.wav");
            AudioClip interior = Clip("Assets/Audio/Horror/Expansion/WORSEN_Interior_Ambience.wav");
            AudioClip exterior = Clip("Assets/Audio/Horror/Expansion/WORSEN_Exterior_Ambience.wav");
            var config = AssetDatabase.LoadAssetAtPath<AudioSoundscapeDriverConfig>(ConfigPath);
            if (config == null) { config = ScriptableObject.CreateInstance<AudioSoundscapeDriverConfig>(); AssetDatabase.CreateAsset(config, ConfigPath); }
            var serialized = new SerializedObject(config);
            var sounds = serialized.FindProperty("_sounds"); sounds.arraySize = banks.Length;
            for (int i = 0; i < banks.Length; i++)
            {
                AudioSoundDefinition bank = banks[i]; var item = sounds.GetArrayElementAtIndex(i);
                item.FindPropertyRelative("Cue").intValue = (int)bank.Cue;
                var clips = item.FindPropertyRelative("Clips"); clips.arraySize = bank.Clips.Length;
                for (int j = 0; j < bank.Clips.Length; j++) clips.GetArrayElementAtIndex(j).objectReferenceValue = bank.Clips[j];
                item.FindPropertyRelative("Gain").floatValue = bank.Gain; item.FindPropertyRelative("GainVariation").floatValue = bank.GainVariation;
                item.FindPropertyRelative("PitchMinimum").floatValue = bank.PitchMinimum; item.FindPropertyRelative("PitchMaximum").floatValue = bank.PitchMaximum;
                item.FindPropertyRelative("Priority").intValue = bank.Priority; item.FindPropertyRelative("Cooldown").floatValue = bank.Cooldown;
                item.FindPropertyRelative("MaxConcurrent").intValue = bank.MaxConcurrent; item.FindPropertyRelative("Spatial").boolValue = bank.Spatial;
                item.FindPropertyRelative("Loop").boolValue = bank.Loop; item.FindPropertyRelative("Ambience").boolValue = bank.Ambience;
                item.FindPropertyRelative("MinimumDistance").floatValue = bank.MinimumDistance; item.FindPropertyRelative("MaximumDistance").floatValue = bank.MaximumDistance;
            }
            serialized.FindProperty("_tensionStem").objectReferenceValue = tension;
            serialized.FindProperty("_chaseStem").objectReferenceValue = stress;
            serialized.FindProperty("_dangerStem").objectReferenceValue = danger;
            serialized.FindProperty("_runIntro").objectReferenceValue = intro;
            serialized.FindProperty("_runLoop").objectReferenceValue = run;
            serialized.FindProperty("_runEnd").objectReferenceValue = ending;
            serialized.FindProperty("_interiorAmbience").objectReferenceValue = interior;
            serialized.FindProperty("_exteriorAmbience").objectReferenceValue = exterior;
            serialized.ApplyModifiedPropertiesWithoutUndo(); EditorUtility.SetDirty(config); AssetDatabase.SaveAssetIfDirty(config);
            var ownerSerialized = new SerializedObject(owner);
            ownerSerialized.FindProperty("_soundscape").objectReferenceValue = config;
            ownerSerialized.FindProperty("_breathLoop").objectReferenceValue = Clip("Assets/Audio/Horror/Expansion/WORSEN_breath_01.wav");
            ownerSerialized.ApplyModifiedPropertiesWithoutUndo(); EditorUtility.SetDirty(owner); AssetDatabase.SaveAssetIfDirty(owner);
            return config;
        }
        private static AudioClip Clip(string path)
        {
            var clip = AssetDatabase.LoadAssetAtPath<AudioClip>(path);
            if (clip == null) throw new InvalidOperationException("Required horror audio clip is missing: " + path);
            return clip;
        }
        private static AudioSoundDefinition[] Banks() => new[]
        {
            new AudioSoundDefinition { Cue = CueId.PostureRustle, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.18f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.12f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 25, MaxConcurrent = 1 },
            new AudioSoundDefinition { Cue = CueId.SprintExertion, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_breath_01.wav") }, Gain = 0.18f, GainVariation = 0.06f, PitchMinimum = 0.98f, PitchMaximum = 1.02f, Cooldown = 0f, Spatial = false, Loop = true, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 30, MaxConcurrent = 1 },
            new AudioSoundDefinition { Cue = CueId.Presence, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Detection, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Chase, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Lose, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Death, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_02.wav") }, Gain = 0.45f, GainVariation = 0.08f, PitchMinimum = 0.82f, PitchMaximum = 0.92f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 90, MaxConcurrent = 1 },
            new AudioSoundDefinition { Cue = CueId.Footstep, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_step_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ExitOpen, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_door_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_door_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.RoomTelegraph, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Jump, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Land, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.SlideStart, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.SlideLoop, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_slide_01.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = true, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.SlideEnd, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_step_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Vault, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.WallRebound, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.FlashlightOn, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.FlashlightOff, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.PlayerHit, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.PlayerCritical, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_breath_01.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = true, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.GrabWarning, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.GrabStart, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.GrabEscape, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.GrabHit, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Consumed, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 90, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.CakeCollect, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_pickup_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_pickup_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_pickup_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.GoldenCakeCollect, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_02.wav") }, Gain = 0.36f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.CakeChain, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyFootstep, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_step_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_step_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyWindup, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyAttack, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyMiss, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyHit, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_hit_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyRecovery, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyScream, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_scream_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 8f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 32f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.EnemyLost, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_growl_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.RoomCrack, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.RoomTear, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_tear_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_tear_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.MistAdvance, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_mist_01.wav") }, Gain = 0.35f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = true, Ambience = true, MinimumDistance = 1.8f, MaximumDistance = 18f, Priority = 15, MaxConcurrent = 4 },
            new AudioSoundDefinition { Cue = CueId.RoomConsumed, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_tear_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_tear_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.TorchLoop, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_fire_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_fire_02.wav") }, Gain = 0.35f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = true, Ambience = true, MinimumDistance = 1.8f, MaximumDistance = 18f, Priority = 15, MaxConcurrent = 4 },
            new AudioSoundDefinition { Cue = CueId.WindLoop, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_mist_01.wav") }, Gain = 0.35f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = true, Ambience = true, MinimumDistance = 1.8f, MaximumDistance = 18f, Priority = 15, MaxConcurrent = 4 },
            new AudioSoundDefinition { Cue = CueId.Drip, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_drip_01.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ChainCreak, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_chain_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_chain_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.DoorOpen, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_door_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_door_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.CurseOffer, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_chain_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_chain_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.CurseSelect, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ShopOpen, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_door_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_door_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ShopBuy, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_02.wav") }, Gain = 0.36f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ShopReject, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_switch_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.UiMove, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.12f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.UiConfirm, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.12f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.UiBack, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_03.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.12f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Heal, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_heal_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_heal_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.WardBreak, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_golden_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.RoundStart, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_door_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_door_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.Restart, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_ui_03.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = false, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ProjectileLaunch, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_swing_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ProjectileTravel, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_mist_01.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = true, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.ProjectileImpact, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_impact_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.SpikeWarning, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_02.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_crack_03.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.SpikeErupt, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_spike_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_spike_02.wav") }, Gain = 0.55f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 80, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.TraversalMiss, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_cloth_02.wav") }, Gain = 0.42f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.FootstepWood, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_stepwood_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_stepwood_02.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.FootstepMetal, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_stepmetal_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_stepmetal_02.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 },
            new AudioSoundDefinition { Cue = CueId.FootstepSoil, Clips = new[] { Clip("Assets/Audio/Horror/Expansion/WORSEN_stepsoil_01.wav"), Clip("Assets/Audio/Horror/Expansion/WORSEN_stepsoil_02.wav") }, Gain = 0.23f, GainVariation = 0.12f, PitchMinimum = 0.94f, PitchMaximum = 1.06f, Cooldown = 0.08f, Spatial = true, Loop = false, Ambience = false, MinimumDistance = 1.8f, MaximumDistance = 20f, Priority = 35, MaxConcurrent = 3 }
        };
    }
}
